<a href="classes/01_initialized.php">Class initialized</a><br>
<a href="classes/02_argument.php">Argument value of the method within the class</a><br>
<a href="classes/03_factorial_mine.php">Calculates the factorial of an integer (mine)</a><br>
<a href="classes/03_factorial.php">Calculates the factorial of an integer </a><br>
<a href="classes/04_sort.php">Sort array</a><br>
<a href="classes/05_difference.php">Difference between two dates (MINE)</a><br><br>
<a href="classes/06_user.php">User class</a><br>
<a href="classes/07_this.php">$this keyword</a><br>
<a href="classes/08_properties.php">Chaining methods and properties</a><br>
<a href="classes/09_private.php">Private access</a><br>
<a href="classes/10_constructor.php">Constructor</a><br>
<a href="classes/11_inheritance.php">Inheritance</a><br>
<a href="classes/12_abstract.php">Abstract class</a><br>
<a href="classes/13_interfaces.php">Interfaces </a><br>
<a href="classes/14_polymorphism.php">Polymorphism </a><br>
